version: '3.8'
services:
  frontend:
    image: 060623761618.dkr.ecr.eu-central-1.amazonaws.com/task/three-tier-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: 060623761618.dkr.ecr.eu-central-1.amazonaws.com/task/three-tier-backend:latest
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydb
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
